### ISSUE TITLE
Schedules takes a long time to load

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#8661] opened 2024-11-15 09:58 UTC
On the monitor page, schedules take a while to load, showing up a few seconds at least after the other information

**Comment by Abhi1992002** [comment] 2024-11-16 08:44
@aarushik93  Yup. Currently, the schedules require all agent IDs, and after getting all the IDs, it fetches the schedule for each ID one by one.  
We need to create endpoints to fetch all the schedules of the user at once.  

I am working on it.

**Comment by Abhi1992002** [comment] 2024-11-16 12:29
@aarushik93 I believe it has been resolved in #8649

**Comment by majdyz** [comment] 2024-11-18 06:59
There is also this issue that could impact the latency of the data being loaded:
https://github.com/Significant-Gravitas/AutoGPT/issues/8683

**Comment by majdyz** [comment] 2024-11-25 05:52
@aarushik93 I'm still not able to reproduce this, is this still happening?

**Comment by Abhi1992002** [comment] 2024-11-25 15:43
@majdyz Basically, what was happening initially was that we fetched all the agents first and then, using their IDs, we fetched all their schedules. That's why it looked a little glitchy, but as we created dedicated endpoints for them, it's working fine now.

[This issue was created before you solved it.]

**Comment by majdyz** [comment] 2024-12-06 16:27
@Abhi1992002 got it, thanks for confirming this!
Closing this ticket.

**Closed by majdyz** 2024-12-06 16:27 UTC
